/*****************************************************************************
 * Automatically generated by Bitman2Base V4.2.5.0 (5.0) Bitman2 (exe) V4.2.5.0 (5.0) - DO NOT EDIT!
 * Generated at 3/23/2009 2:35:11 PM
 *
 * Project : Baxter Peak
 * Module  : L3 Monitor groups
 * Author  : Nir BM
 * Date    : 21/5/2007
 *****************************************************************************/

#if !defined(_BITMAN_L4MONITORGROUPS_H_)
#define _BITMAN_L4MONITORGROUPS_H_


/*lint ++flb */
// Include the Bitman common header file
#include "BitmanCommon.h"

// Include headers generated from XMLs (the source is both XMLs and the command-line)
#include "BasicBitmanTypes.h"

// Include user C header files

// Include user C header files (supplied in the command-line)


// Bitman version Accessor...
#ifndef BM_BITMAN_VERSION
#define BM_BITMAN_VERSION 	"Bitman2Base V4.2.5.0 (5.0) Bitman2 (exe) V4.2.5.0 (5.0)"
#endif 

// Definitions

typedef UINT8 DnDUtils_Statistics[24];

/*lint -save -e806 */ /* Small bit field is signed rather than unsigned*/
#ifdef BMI_ENDIANNESS_LITTLE
#if (!defined __arm && !defined __arc)
#pragma pack( push, 1 )
#endif
#ifdef __arm
typedef __packed struct
#elif defined __arc
typedef _Packed struct
#else
typedef struct
#endif
{
	UINT32 _TotalNumOfMessages; //Total number of messages added to the queue from the device
	UINT32 _TotalSizeInBytes; //Total size in bytes of all messages added to the queue from the device
	UINT32 _LastMessageSizeInBytes; //Size in bytes of the last message added to the queue from the device
	UINT32 _NumberOfLostMessagesRaised; //The number of times the dnd agent raised an override message
	UINT32 _NumberOfMessagesInQueue; //The number of messages in the queue when reported
	UINT16 _CurrentFileIndex; //The index of the file we are currently writing to
} BMS_DnDUtils_Statistics;

#if (!defined __arm && !defined __arc)
#pragma pack( pop )
#endif

#else /* BMI_ENDIANNESS_BIG */
#if (!defined __arm && !defined __arc)
#pragma pack( push, 1 )
#endif
#ifdef __arm
typedef __packed struct
#elif defined __arc
typedef _Packed struct
#else
typedef struct
#endif
{
	UINT16 _CurrentFileIndex; //The index of the file we are currently writing to
	UINT32 _NumberOfMessagesInQueue; //The number of messages in the queue when reported
	UINT32 _NumberOfLostMessagesRaised; //The number of times the dnd agent raised an override message
	UINT32 _LastMessageSizeInBytes; //Size in bytes of the last message added to the queue from the device
	UINT32 _TotalSizeInBytes; //Total size in bytes of all messages added to the queue from the device
	UINT32 _TotalNumOfMessages; //Total number of messages added to the queue from the device
} BMS_DnDUtils_Statistics;

#if (!defined __arm && !defined __arc)
#pragma pack( pop )
#endif

#endif	/*#ifdef BMI_ENDIANNESS_LITTLE*/
/*lint -restore */

// COMPOSITE: Full name: 'DnDUtils_Statistics' Type: 'DnDUtils_Statistics', Top-level, Non-instance, No bitoff root
#define BM_DnDUtils_Statistics_TotalNumOfMessages_GET_POS( base_ptr, out_ptr, out_bitoff )\
{\
	/*lint --e{*} */\
	out_ptr = base_ptr;\
	out_bitoff = 0;\
}

#define BM_DnDUtils_Statistics_TotalNumOfMessages_GET_POS_ALIGNED( base_ptr, out_ptr )\
{\
	/*lint --e{*} */\
	UINT bmlocal79_tmp_bitoff;\
	BM_DnDUtils_Statistics_TotalNumOfMessages_GET_POS( base_ptr, out_ptr, bmlocal79_tmp_bitoff );\
	BMI_NORMALIZE_BITOFF(out_ptr, bmlocal79_tmp_bitoff);\
}

#define BM_DnDUtils_Statistics_TotalNumOfMessages_POS_ALIGNED 0

// Alignment of DnDUtils_Statistics_TotalNumOfMessages: accumulated=(0,0, ABA=4), parent.base=(0,0, ABA=4)
#define BM_DnDUtils_Statistics_TotalNumOfMessages_GET_SIZE( base_ptr, out_bytes, out_bits )\
{\
	/*lint --e{*} */\
	out_bytes = 4;\
	out_bits = 0;\
	BMI_UNUSED_VAR( base_ptr );\
}

#define BM_DnDUtils_Statistics_TotalNumOfMessages_GET( base_ptr, out_val )\
{\
	/*lint --e{*} */\
	PVOID bmlocal80_my_ptr;\
	UINT bmlocal81_my_bitoff;\
	BM_DnDUtils_Statistics_TotalNumOfMessages_GET_POS( base_ptr, bmlocal80_my_ptr, bmlocal81_my_bitoff );\
	if( BMI_MACHINE_ARM_LITTLE == BMI_MACHINE_VALUE )\
	{\
		(out_val) = (UINT32)BMI_32BIT_EXTRACT( (BMI_GET_32BIT_PTR_CONTENTS( BMI_PTR_TO_NUMERIC_CAST(bmlocal80_my_ptr)) ), 0, 32, 0);\
	}\
	else if( BMI_MACHINE_INTEL_LITTLE == BMI_MACHINE_VALUE )\
	{\
		(out_val) = (UINT32)BMI_32BIT_EXTRACT( (BMI_GET_32BIT_PTR_CONTENTS( BMI_PTR_TO_NUMERIC_CAST(bmlocal80_my_ptr)) ), 0, 32, 0);\
	}\
	else\
	{\
		BMI_GENERIC_32BIT_LITTLE_GET( bmlocal80_my_ptr, bmlocal81_my_bitoff, 32, UINT32, out_val, 0x00000000 );\
	}\
}

BMI_INLINE UINT32 BM_INLINE_DnDUtils_Statistics_TotalNumOfMessages_GET(PVOID base_ptr)
{
	/*lint --e{*} */
	UINT32 bmlocal82_tmp_var;
	BM_DnDUtils_Statistics_TotalNumOfMessages_GET( base_ptr, bmlocal82_tmp_var );
	return bmlocal82_tmp_var;
}

#define BM_DnDUtils_Statistics_TotalNumOfMessages_SET( base_ptr, in_val )\
{\
	/*lint --e{*} */\
	PVOID bmlocal83_my_ptr;\
	UINT bmlocal84_my_bitoff;\
	BM_DnDUtils_Statistics_TotalNumOfMessages_GET_POS( base_ptr, bmlocal83_my_ptr, bmlocal84_my_bitoff );\
	if( BMI_MACHINE_ARM_LITTLE == BMI_MACHINE_VALUE )\
	{\
		BMI_32BIT_CLEAR_ASSIGN_TYPE( BMI_GET_32BIT_PTR_CONTENTS( BMI_PTR_TO_NUMERIC_CAST(bmlocal83_my_ptr) ), (in_val), 0, 0, 32, UINT32 );\
	}\
	else if( BMI_MACHINE_INTEL_LITTLE == BMI_MACHINE_VALUE )\
	{\
		BMI_32BIT_CLEAR_ASSIGN_TYPE( BMI_GET_32BIT_PTR_CONTENTS( BMI_PTR_TO_NUMERIC_CAST(bmlocal83_my_ptr) ), (in_val), 0, 0, 32, UINT32 );\
	}\
	else\
	{\
		BMI_GENERIC_32BIT_LITTLE_SET( bmlocal83_my_ptr, bmlocal84_my_bitoff, 32, in_val, 0x00000000 );\
	}\
}

// DnDUtils_Statistics_TotalNumOfMessages: IS_DEFAULT accessor is not defined because no default value was specified.
// DnDUtils_Statistics_TotalNumOfMessages: SET_DEFAULT accessor is not defined because no default value was specified.
// DnDUtils_Statistics_TotalNumOfMessages: IS_RESET accessor is not defined because no reset value was specified.
// DnDUtils_Statistics_TotalNumOfMessages: SET_RESET accessor is not defined because no reset value was specified.
// DnDUtils_Statistics_TotalNumOfMessages: CLEAR accessor is not defined because of incompatible access rights. Specified: RW Required: W1C, WO1C.
// DnDUtils_Statistics_TotalNumOfMessages: SET(W1S) accessor is not defined because of incompatible access rights. Specified: RW Required: W1S, WO1S.
#define BM_DnDUtils_Statistics_TotalNumOfMessages_DUMP_DEPTH( base_ptr, depth )\
{\
	/*lint --e{*} */\
	UINT32 bmlocal85_out_val;\
	BM_DnDUtils_Statistics_TotalNumOfMessages_GET( base_ptr, bmlocal85_out_val );\
	/*lint -e(571) */\
	BMI_FORMAT_DUMP(depth, "TotalNumOfMessages", 32, (UINT)(bmlocal85_out_val), "%d", 1);\
}

#define BM_DnDUtils_Statistics_TotalNumOfMessages_DUMP( base_ptr )\
{\
	/*lint --e{*} */\
	BM_DnDUtils_Statistics_TotalNumOfMessages_DUMP_DEPTH( base_ptr, 0 );\
}

#define BM_DnDUtils_Statistics_TotalNumOfMessages_INCREMENT( base_ptr )\
{\
	/*lint --e{*} */\
	PVOID bmlocal86_my_ptr;\
	UINT bmlocal87_my_bitoff;\
	BM_DnDUtils_Statistics_TotalNumOfMessages_GET_POS( base_ptr, bmlocal86_my_ptr, bmlocal87_my_bitoff );\
	(*((UINT32*)bmlocal86_my_ptr))++;\
	BMI_UNUSED_VAR( bmlocal87_my_bitoff );\
}

// DnDUtils_Statistics_TotalNumOfMessages: Validation accessors are not defined because validation condition was not specified.
#define BM_DnDUtils_Statistics_TotalNumOfMessages_GET_BYTES_SIZE( base_ptr, out_bytes )\
{\
	/*lint --e{*} */\
	UINT bmlocal88_tmp_bits;\
	BM_DnDUtils_Statistics_TotalNumOfMessages_GET_SIZE( base_ptr, out_bytes, bmlocal88_tmp_bits );\
	BMI_ROUND_UP_1BYTES( out_bytes, bmlocal88_tmp_bits );\
}

#define BM_DnDUtils_Statistics_TotalNumOfMessages_BYTES_SIZE 4

#define BM_DnDUtils_Statistics_TotalSizeInBytes_GET_POS( base_ptr, out_ptr, out_bitoff )\
{\
	/*lint --e{*} */\
	UINT bmlocal91_acc_bytes;\
	UINT bmlocal92_acc_bits;\
	out_ptr = base_ptr;\
	out_bitoff = 0;\
	bmlocal91_acc_bytes = 4;\
	bmlocal92_acc_bits = 0;\
	BMI_ADD_ASSIGN_PTR( out_ptr, bmlocal91_acc_bytes );\
	out_bitoff += bmlocal92_acc_bits;\
}

#define BM_DnDUtils_Statistics_TotalSizeInBytes_GET_POS_ALIGNED( base_ptr, out_ptr )\
{\
	/*lint --e{*} */\
	UINT bmlocal93_tmp_bitoff;\
	BM_DnDUtils_Statistics_TotalSizeInBytes_GET_POS( base_ptr, out_ptr, bmlocal93_tmp_bitoff );\
	BMI_NORMALIZE_BITOFF(out_ptr, bmlocal93_tmp_bitoff);\
}

#define BM_DnDUtils_Statistics_TotalSizeInBytes_POS_ALIGNED 4

// Alignment of DnDUtils_Statistics_TotalSizeInBytes: accumulated=(0,0, ABA=4), parent.base=(0,0, ABA=4)
#define BM_DnDUtils_Statistics_TotalSizeInBytes_GET_SIZE( base_ptr, out_bytes, out_bits )\
{\
	/*lint --e{*} */\
	out_bytes = 4;\
	out_bits = 0;\
	BMI_UNUSED_VAR( base_ptr );\
}

#define BM_DnDUtils_Statistics_TotalSizeInBytes_GET( base_ptr, out_val )\
{\
	/*lint --e{*} */\
	PVOID bmlocal94_my_ptr;\
	UINT bmlocal95_my_bitoff;\
	BM_DnDUtils_Statistics_TotalSizeInBytes_GET_POS( base_ptr, bmlocal94_my_ptr, bmlocal95_my_bitoff );\
	if( BMI_MACHINE_ARM_LITTLE == BMI_MACHINE_VALUE )\
	{\
		(out_val) = (UINT32)BMI_32BIT_EXTRACT( (BMI_GET_32BIT_PTR_CONTENTS( BMI_PTR_TO_NUMERIC_CAST(bmlocal94_my_ptr)) ), 0, 32, 0);\
	}\
	else if( BMI_MACHINE_INTEL_LITTLE == BMI_MACHINE_VALUE )\
	{\
		(out_val) = (UINT32)BMI_32BIT_EXTRACT( (BMI_GET_32BIT_PTR_CONTENTS( BMI_PTR_TO_NUMERIC_CAST(bmlocal94_my_ptr)) ), 0, 32, 0);\
	}\
	else\
	{\
		BMI_GENERIC_32BIT_LITTLE_GET( bmlocal94_my_ptr, bmlocal95_my_bitoff, 32, UINT32, out_val, 0x00000000 );\
	}\
}

BMI_INLINE UINT32 BM_INLINE_DnDUtils_Statistics_TotalSizeInBytes_GET(PVOID base_ptr)
{
	/*lint --e{*} */
	UINT32 bmlocal96_tmp_var;
	BM_DnDUtils_Statistics_TotalSizeInBytes_GET( base_ptr, bmlocal96_tmp_var );
	return bmlocal96_tmp_var;
}

#define BM_DnDUtils_Statistics_TotalSizeInBytes_SET( base_ptr, in_val )\
{\
	/*lint --e{*} */\
	PVOID bmlocal97_my_ptr;\
	UINT bmlocal98_my_bitoff;\
	BM_DnDUtils_Statistics_TotalSizeInBytes_GET_POS( base_ptr, bmlocal97_my_ptr, bmlocal98_my_bitoff );\
	if( BMI_MACHINE_ARM_LITTLE == BMI_MACHINE_VALUE )\
	{\
		BMI_32BIT_CLEAR_ASSIGN_TYPE( BMI_GET_32BIT_PTR_CONTENTS( BMI_PTR_TO_NUMERIC_CAST(bmlocal97_my_ptr) ), (in_val), 0, 0, 32, UINT32 );\
	}\
	else if( BMI_MACHINE_INTEL_LITTLE == BMI_MACHINE_VALUE )\
	{\
		BMI_32BIT_CLEAR_ASSIGN_TYPE( BMI_GET_32BIT_PTR_CONTENTS( BMI_PTR_TO_NUMERIC_CAST(bmlocal97_my_ptr) ), (in_val), 0, 0, 32, UINT32 );\
	}\
	else\
	{\
		BMI_GENERIC_32BIT_LITTLE_SET( bmlocal97_my_ptr, bmlocal98_my_bitoff, 32, in_val, 0x00000000 );\
	}\
}

// DnDUtils_Statistics_TotalSizeInBytes: IS_DEFAULT accessor is not defined because no default value was specified.
// DnDUtils_Statistics_TotalSizeInBytes: SET_DEFAULT accessor is not defined because no default value was specified.
// DnDUtils_Statistics_TotalSizeInBytes: IS_RESET accessor is not defined because no reset value was specified.
// DnDUtils_Statistics_TotalSizeInBytes: SET_RESET accessor is not defined because no reset value was specified.
// DnDUtils_Statistics_TotalSizeInBytes: CLEAR accessor is not defined because of incompatible access rights. Specified: RW Required: W1C, WO1C.
// DnDUtils_Statistics_TotalSizeInBytes: SET(W1S) accessor is not defined because of incompatible access rights. Specified: RW Required: W1S, WO1S.
#define BM_DnDUtils_Statistics_TotalSizeInBytes_DUMP_DEPTH( base_ptr, depth )\
{\
	/*lint --e{*} */\
	UINT32 bmlocal99_out_val;\
	BM_DnDUtils_Statistics_TotalSizeInBytes_GET( base_ptr, bmlocal99_out_val );\
	/*lint -e(571) */\
	BMI_FORMAT_DUMP(depth, "TotalSizeInBytes", 32, (UINT)(bmlocal99_out_val), "%d", 1);\
}

#define BM_DnDUtils_Statistics_TotalSizeInBytes_DUMP( base_ptr )\
{\
	/*lint --e{*} */\
	BM_DnDUtils_Statistics_TotalSizeInBytes_DUMP_DEPTH( base_ptr, 0 );\
}

#define BM_DnDUtils_Statistics_TotalSizeInBytes_INCREMENT( base_ptr )\
{\
	/*lint --e{*} */\
	PVOID bmlocal100_my_ptr;\
	UINT bmlocal101_my_bitoff;\
	BM_DnDUtils_Statistics_TotalSizeInBytes_GET_POS( base_ptr, bmlocal100_my_ptr, bmlocal101_my_bitoff );\
	(*((UINT32*)bmlocal100_my_ptr))++;\
	BMI_UNUSED_VAR( bmlocal101_my_bitoff );\
}

// DnDUtils_Statistics_TotalSizeInBytes: Validation accessors are not defined because validation condition was not specified.
#define BM_DnDUtils_Statistics_TotalSizeInBytes_GET_BYTES_SIZE( base_ptr, out_bytes )\
{\
	/*lint --e{*} */\
	UINT bmlocal102_tmp_bits;\
	BM_DnDUtils_Statistics_TotalSizeInBytes_GET_SIZE( base_ptr, out_bytes, bmlocal102_tmp_bits );\
	BMI_ROUND_UP_1BYTES( out_bytes, bmlocal102_tmp_bits );\
}

#define BM_DnDUtils_Statistics_TotalSizeInBytes_BYTES_SIZE 4

#define BM_DnDUtils_Statistics_LastMessageSizeInBytes_GET_POS( base_ptr, out_ptr, out_bitoff )\
{\
	/*lint --e{*} */\
	UINT bmlocal105_acc_bytes;\
	UINT bmlocal106_acc_bits;\
	out_ptr = base_ptr;\
	out_bitoff = 0;\
	bmlocal105_acc_bytes = 8;\
	bmlocal106_acc_bits = 0;\
	BMI_ADD_ASSIGN_PTR( out_ptr, bmlocal105_acc_bytes );\
	out_bitoff += bmlocal106_acc_bits;\
}

#define BM_DnDUtils_Statistics_LastMessageSizeInBytes_GET_POS_ALIGNED( base_ptr, out_ptr )\
{\
	/*lint --e{*} */\
	UINT bmlocal107_tmp_bitoff;\
	BM_DnDUtils_Statistics_LastMessageSizeInBytes_GET_POS( base_ptr, out_ptr, bmlocal107_tmp_bitoff );\
	BMI_NORMALIZE_BITOFF(out_ptr, bmlocal107_tmp_bitoff);\
}

#define BM_DnDUtils_Statistics_LastMessageSizeInBytes_POS_ALIGNED 8

// Alignment of DnDUtils_Statistics_LastMessageSizeInBytes: accumulated=(0,0, ABA=4), parent.base=(0,0, ABA=4)
#define BM_DnDUtils_Statistics_LastMessageSizeInBytes_GET_SIZE( base_ptr, out_bytes, out_bits )\
{\
	/*lint --e{*} */\
	out_bytes = 4;\
	out_bits = 0;\
	BMI_UNUSED_VAR( base_ptr );\
}

#define BM_DnDUtils_Statistics_LastMessageSizeInBytes_GET( base_ptr, out_val )\
{\
	/*lint --e{*} */\
	PVOID bmlocal108_my_ptr;\
	UINT bmlocal109_my_bitoff;\
	BM_DnDUtils_Statistics_LastMessageSizeInBytes_GET_POS( base_ptr, bmlocal108_my_ptr, bmlocal109_my_bitoff );\
	if( BMI_MACHINE_ARM_LITTLE == BMI_MACHINE_VALUE )\
	{\
		(out_val) = (UINT32)BMI_32BIT_EXTRACT( (BMI_GET_32BIT_PTR_CONTENTS( BMI_PTR_TO_NUMERIC_CAST(bmlocal108_my_ptr)) ), 0, 32, 0);\
	}\
	else if( BMI_MACHINE_INTEL_LITTLE == BMI_MACHINE_VALUE )\
	{\
		(out_val) = (UINT32)BMI_32BIT_EXTRACT( (BMI_GET_32BIT_PTR_CONTENTS( BMI_PTR_TO_NUMERIC_CAST(bmlocal108_my_ptr)) ), 0, 32, 0);\
	}\
	else\
	{\
		BMI_GENERIC_32BIT_LITTLE_GET( bmlocal108_my_ptr, bmlocal109_my_bitoff, 32, UINT32, out_val, 0x00000000 );\
	}\
}

BMI_INLINE UINT32 BM_INLINE_DnDUtils_Statistics_LastMessageSizeInBytes_GET(PVOID base_ptr)
{
	/*lint --e{*} */
	UINT32 bmlocal110_tmp_var;
	BM_DnDUtils_Statistics_LastMessageSizeInBytes_GET( base_ptr, bmlocal110_tmp_var );
	return bmlocal110_tmp_var;
}

#define BM_DnDUtils_Statistics_LastMessageSizeInBytes_SET( base_ptr, in_val )\
{\
	/*lint --e{*} */\
	PVOID bmlocal111_my_ptr;\
	UINT bmlocal112_my_bitoff;\
	BM_DnDUtils_Statistics_LastMessageSizeInBytes_GET_POS( base_ptr, bmlocal111_my_ptr, bmlocal112_my_bitoff );\
	if( BMI_MACHINE_ARM_LITTLE == BMI_MACHINE_VALUE )\
	{\
		BMI_32BIT_CLEAR_ASSIGN_TYPE( BMI_GET_32BIT_PTR_CONTENTS( BMI_PTR_TO_NUMERIC_CAST(bmlocal111_my_ptr) ), (in_val), 0, 0, 32, UINT32 );\
	}\
	else if( BMI_MACHINE_INTEL_LITTLE == BMI_MACHINE_VALUE )\
	{\
		BMI_32BIT_CLEAR_ASSIGN_TYPE( BMI_GET_32BIT_PTR_CONTENTS( BMI_PTR_TO_NUMERIC_CAST(bmlocal111_my_ptr) ), (in_val), 0, 0, 32, UINT32 );\
	}\
	else\
	{\
		BMI_GENERIC_32BIT_LITTLE_SET( bmlocal111_my_ptr, bmlocal112_my_bitoff, 32, in_val, 0x00000000 );\
	}\
}

// DnDUtils_Statistics_LastMessageSizeInBytes: IS_DEFAULT accessor is not defined because no default value was specified.
// DnDUtils_Statistics_LastMessageSizeInBytes: SET_DEFAULT accessor is not defined because no default value was specified.
// DnDUtils_Statistics_LastMessageSizeInBytes: IS_RESET accessor is not defined because no reset value was specified.
// DnDUtils_Statistics_LastMessageSizeInBytes: SET_RESET accessor is not defined because no reset value was specified.
// DnDUtils_Statistics_LastMessageSizeInBytes: CLEAR accessor is not defined because of incompatible access rights. Specified: RW Required: W1C, WO1C.
// DnDUtils_Statistics_LastMessageSizeInBytes: SET(W1S) accessor is not defined because of incompatible access rights. Specified: RW Required: W1S, WO1S.
#define BM_DnDUtils_Statistics_LastMessageSizeInBytes_DUMP_DEPTH( base_ptr, depth )\
{\
	/*lint --e{*} */\
	UINT32 bmlocal113_out_val;\
	BM_DnDUtils_Statistics_LastMessageSizeInBytes_GET( base_ptr, bmlocal113_out_val );\
	/*lint -e(571) */\
	BMI_FORMAT_DUMP(depth, "LastMessageSizeInBytes", 32, (UINT)(bmlocal113_out_val), "%d", 1);\
}

#define BM_DnDUtils_Statistics_LastMessageSizeInBytes_DUMP( base_ptr )\
{\
	/*lint --e{*} */\
	BM_DnDUtils_Statistics_LastMessageSizeInBytes_DUMP_DEPTH( base_ptr, 0 );\
}

#define BM_DnDUtils_Statistics_LastMessageSizeInBytes_INCREMENT( base_ptr )\
{\
	/*lint --e{*} */\
	PVOID bmlocal114_my_ptr;\
	UINT bmlocal115_my_bitoff;\
	BM_DnDUtils_Statistics_LastMessageSizeInBytes_GET_POS( base_ptr, bmlocal114_my_ptr, bmlocal115_my_bitoff );\
	(*((UINT32*)bmlocal114_my_ptr))++;\
	BMI_UNUSED_VAR( bmlocal115_my_bitoff );\
}

// DnDUtils_Statistics_LastMessageSizeInBytes: Validation accessors are not defined because validation condition was not specified.
#define BM_DnDUtils_Statistics_LastMessageSizeInBytes_GET_BYTES_SIZE( base_ptr, out_bytes )\
{\
	/*lint --e{*} */\
	UINT bmlocal116_tmp_bits;\
	BM_DnDUtils_Statistics_LastMessageSizeInBytes_GET_SIZE( base_ptr, out_bytes, bmlocal116_tmp_bits );\
	BMI_ROUND_UP_1BYTES( out_bytes, bmlocal116_tmp_bits );\
}

#define BM_DnDUtils_Statistics_LastMessageSizeInBytes_BYTES_SIZE 4

#define BM_DnDUtils_Statistics_NumberOfLostMessagesRaised_GET_POS( base_ptr, out_ptr, out_bitoff )\
{\
	/*lint --e{*} */\
	UINT bmlocal119_acc_bytes;\
	UINT bmlocal120_acc_bits;\
	out_ptr = base_ptr;\
	out_bitoff = 0;\
	bmlocal119_acc_bytes = 12;\
	bmlocal120_acc_bits = 0;\
	BMI_ADD_ASSIGN_PTR( out_ptr, bmlocal119_acc_bytes );\
	out_bitoff += bmlocal120_acc_bits;\
}

#define BM_DnDUtils_Statistics_NumberOfLostMessagesRaised_GET_POS_ALIGNED( base_ptr, out_ptr )\
{\
	/*lint --e{*} */\
	UINT bmlocal121_tmp_bitoff;\
	BM_DnDUtils_Statistics_NumberOfLostMessagesRaised_GET_POS( base_ptr, out_ptr, bmlocal121_tmp_bitoff );\
	BMI_NORMALIZE_BITOFF(out_ptr, bmlocal121_tmp_bitoff);\
}

#define BM_DnDUtils_Statistics_NumberOfLostMessagesRaised_POS_ALIGNED 12

// Alignment of DnDUtils_Statistics_NumberOfLostMessagesRaised: accumulated=(0,0, ABA=4), parent.base=(0,0, ABA=4)
#define BM_DnDUtils_Statistics_NumberOfLostMessagesRaised_GET_SIZE( base_ptr, out_bytes, out_bits )\
{\
	/*lint --e{*} */\
	out_bytes = 4;\
	out_bits = 0;\
	BMI_UNUSED_VAR( base_ptr );\
}

#define BM_DnDUtils_Statistics_NumberOfLostMessagesRaised_GET( base_ptr, out_val )\
{\
	/*lint --e{*} */\
	PVOID bmlocal122_my_ptr;\
	UINT bmlocal123_my_bitoff;\
	BM_DnDUtils_Statistics_NumberOfLostMessagesRaised_GET_POS( base_ptr, bmlocal122_my_ptr, bmlocal123_my_bitoff );\
	if( BMI_MACHINE_ARM_LITTLE == BMI_MACHINE_VALUE )\
	{\
		(out_val) = (UINT32)BMI_32BIT_EXTRACT( (BMI_GET_32BIT_PTR_CONTENTS( BMI_PTR_TO_NUMERIC_CAST(bmlocal122_my_ptr)) ), 0, 32, 0);\
	}\
	else if( BMI_MACHINE_INTEL_LITTLE == BMI_MACHINE_VALUE )\
	{\
		(out_val) = (UINT32)BMI_32BIT_EXTRACT( (BMI_GET_32BIT_PTR_CONTENTS( BMI_PTR_TO_NUMERIC_CAST(bmlocal122_my_ptr)) ), 0, 32, 0);\
	}\
	else\
	{\
		BMI_GENERIC_32BIT_LITTLE_GET( bmlocal122_my_ptr, bmlocal123_my_bitoff, 32, UINT32, out_val, 0x00000000 );\
	}\
}

BMI_INLINE UINT32 BM_INLINE_DnDUtils_Statistics_NumberOfLostMessagesRaised_GET(PVOID base_ptr)
{
	/*lint --e{*} */
	UINT32 bmlocal124_tmp_var;
	BM_DnDUtils_Statistics_NumberOfLostMessagesRaised_GET( base_ptr, bmlocal124_tmp_var );
	return bmlocal124_tmp_var;
}

#define BM_DnDUtils_Statistics_NumberOfLostMessagesRaised_SET( base_ptr, in_val )\
{\
	/*lint --e{*} */\
	PVOID bmlocal125_my_ptr;\
	UINT bmlocal126_my_bitoff;\
	BM_DnDUtils_Statistics_NumberOfLostMessagesRaised_GET_POS( base_ptr, bmlocal125_my_ptr, bmlocal126_my_bitoff );\
	if( BMI_MACHINE_ARM_LITTLE == BMI_MACHINE_VALUE )\
	{\
		BMI_32BIT_CLEAR_ASSIGN_TYPE( BMI_GET_32BIT_PTR_CONTENTS( BMI_PTR_TO_NUMERIC_CAST(bmlocal125_my_ptr) ), (in_val), 0, 0, 32, UINT32 );\
	}\
	else if( BMI_MACHINE_INTEL_LITTLE == BMI_MACHINE_VALUE )\
	{\
		BMI_32BIT_CLEAR_ASSIGN_TYPE( BMI_GET_32BIT_PTR_CONTENTS( BMI_PTR_TO_NUMERIC_CAST(bmlocal125_my_ptr) ), (in_val), 0, 0, 32, UINT32 );\
	}\
	else\
	{\
		BMI_GENERIC_32BIT_LITTLE_SET( bmlocal125_my_ptr, bmlocal126_my_bitoff, 32, in_val, 0x00000000 );\
	}\
}

// DnDUtils_Statistics_NumberOfLostMessagesRaised: IS_DEFAULT accessor is not defined because no default value was specified.
// DnDUtils_Statistics_NumberOfLostMessagesRaised: SET_DEFAULT accessor is not defined because no default value was specified.
// DnDUtils_Statistics_NumberOfLostMessagesRaised: IS_RESET accessor is not defined because no reset value was specified.
// DnDUtils_Statistics_NumberOfLostMessagesRaised: SET_RESET accessor is not defined because no reset value was specified.
// DnDUtils_Statistics_NumberOfLostMessagesRaised: CLEAR accessor is not defined because of incompatible access rights. Specified: RW Required: W1C, WO1C.
// DnDUtils_Statistics_NumberOfLostMessagesRaised: SET(W1S) accessor is not defined because of incompatible access rights. Specified: RW Required: W1S, WO1S.
#define BM_DnDUtils_Statistics_NumberOfLostMessagesRaised_DUMP_DEPTH( base_ptr, depth )\
{\
	/*lint --e{*} */\
	UINT32 bmlocal127_out_val;\
	BM_DnDUtils_Statistics_NumberOfLostMessagesRaised_GET( base_ptr, bmlocal127_out_val );\
	/*lint -e(571) */\
	BMI_FORMAT_DUMP(depth, "NumberOfLostMessagesRaised", 32, (UINT)(bmlocal127_out_val), "%d", 1);\
}

#define BM_DnDUtils_Statistics_NumberOfLostMessagesRaised_DUMP( base_ptr )\
{\
	/*lint --e{*} */\
	BM_DnDUtils_Statistics_NumberOfLostMessagesRaised_DUMP_DEPTH( base_ptr, 0 );\
}

#define BM_DnDUtils_Statistics_NumberOfLostMessagesRaised_INCREMENT( base_ptr )\
{\
	/*lint --e{*} */\
	PVOID bmlocal128_my_ptr;\
	UINT bmlocal129_my_bitoff;\
	BM_DnDUtils_Statistics_NumberOfLostMessagesRaised_GET_POS( base_ptr, bmlocal128_my_ptr, bmlocal129_my_bitoff );\
	(*((UINT32*)bmlocal128_my_ptr))++;\
	BMI_UNUSED_VAR( bmlocal129_my_bitoff );\
}

// DnDUtils_Statistics_NumberOfLostMessagesRaised: Validation accessors are not defined because validation condition was not specified.
#define BM_DnDUtils_Statistics_NumberOfLostMessagesRaised_GET_BYTES_SIZE( base_ptr, out_bytes )\
{\
	/*lint --e{*} */\
	UINT bmlocal130_tmp_bits;\
	BM_DnDUtils_Statistics_NumberOfLostMessagesRaised_GET_SIZE( base_ptr, out_bytes, bmlocal130_tmp_bits );\
	BMI_ROUND_UP_1BYTES( out_bytes, bmlocal130_tmp_bits );\
}

#define BM_DnDUtils_Statistics_NumberOfLostMessagesRaised_BYTES_SIZE 4

#define BM_DnDUtils_Statistics_NumberOfMessagesInQueue_GET_POS( base_ptr, out_ptr, out_bitoff )\
{\
	/*lint --e{*} */\
	UINT bmlocal133_acc_bytes;\
	UINT bmlocal134_acc_bits;\
	out_ptr = base_ptr;\
	out_bitoff = 0;\
	bmlocal133_acc_bytes = 16;\
	bmlocal134_acc_bits = 0;\
	BMI_ADD_ASSIGN_PTR( out_ptr, bmlocal133_acc_bytes );\
	out_bitoff += bmlocal134_acc_bits;\
}

#define BM_DnDUtils_Statistics_NumberOfMessagesInQueue_GET_POS_ALIGNED( base_ptr, out_ptr )\
{\
	/*lint --e{*} */\
	UINT bmlocal135_tmp_bitoff;\
	BM_DnDUtils_Statistics_NumberOfMessagesInQueue_GET_POS( base_ptr, out_ptr, bmlocal135_tmp_bitoff );\
	BMI_NORMALIZE_BITOFF(out_ptr, bmlocal135_tmp_bitoff);\
}

#define BM_DnDUtils_Statistics_NumberOfMessagesInQueue_POS_ALIGNED 16

// Alignment of DnDUtils_Statistics_NumberOfMessagesInQueue: accumulated=(0,0, ABA=4), parent.base=(0,0, ABA=4)
#define BM_DnDUtils_Statistics_NumberOfMessagesInQueue_GET_SIZE( base_ptr, out_bytes, out_bits )\
{\
	/*lint --e{*} */\
	out_bytes = 4;\
	out_bits = 0;\
	BMI_UNUSED_VAR( base_ptr );\
}

#define BM_DnDUtils_Statistics_NumberOfMessagesInQueue_GET( base_ptr, out_val )\
{\
	/*lint --e{*} */\
	PVOID bmlocal136_my_ptr;\
	UINT bmlocal137_my_bitoff;\
	BM_DnDUtils_Statistics_NumberOfMessagesInQueue_GET_POS( base_ptr, bmlocal136_my_ptr, bmlocal137_my_bitoff );\
	if( BMI_MACHINE_ARM_LITTLE == BMI_MACHINE_VALUE )\
	{\
		(out_val) = (UINT32)BMI_32BIT_EXTRACT( (BMI_GET_32BIT_PTR_CONTENTS( BMI_PTR_TO_NUMERIC_CAST(bmlocal136_my_ptr)) ), 0, 32, 0);\
	}\
	else if( BMI_MACHINE_INTEL_LITTLE == BMI_MACHINE_VALUE )\
	{\
		(out_val) = (UINT32)BMI_32BIT_EXTRACT( (BMI_GET_32BIT_PTR_CONTENTS( BMI_PTR_TO_NUMERIC_CAST(bmlocal136_my_ptr)) ), 0, 32, 0);\
	}\
	else\
	{\
		BMI_GENERIC_32BIT_LITTLE_GET( bmlocal136_my_ptr, bmlocal137_my_bitoff, 32, UINT32, out_val, 0x00000000 );\
	}\
}

BMI_INLINE UINT32 BM_INLINE_DnDUtils_Statistics_NumberOfMessagesInQueue_GET(PVOID base_ptr)
{
	/*lint --e{*} */
	UINT32 bmlocal138_tmp_var;
	BM_DnDUtils_Statistics_NumberOfMessagesInQueue_GET( base_ptr, bmlocal138_tmp_var );
	return bmlocal138_tmp_var;
}

#define BM_DnDUtils_Statistics_NumberOfMessagesInQueue_SET( base_ptr, in_val )\
{\
	/*lint --e{*} */\
	PVOID bmlocal139_my_ptr;\
	UINT bmlocal140_my_bitoff;\
	BM_DnDUtils_Statistics_NumberOfMessagesInQueue_GET_POS( base_ptr, bmlocal139_my_ptr, bmlocal140_my_bitoff );\
	if( BMI_MACHINE_ARM_LITTLE == BMI_MACHINE_VALUE )\
	{\
		BMI_32BIT_CLEAR_ASSIGN_TYPE( BMI_GET_32BIT_PTR_CONTENTS( BMI_PTR_TO_NUMERIC_CAST(bmlocal139_my_ptr) ), (in_val), 0, 0, 32, UINT32 );\
	}\
	else if( BMI_MACHINE_INTEL_LITTLE == BMI_MACHINE_VALUE )\
	{\
		BMI_32BIT_CLEAR_ASSIGN_TYPE( BMI_GET_32BIT_PTR_CONTENTS( BMI_PTR_TO_NUMERIC_CAST(bmlocal139_my_ptr) ), (in_val), 0, 0, 32, UINT32 );\
	}\
	else\
	{\
		BMI_GENERIC_32BIT_LITTLE_SET( bmlocal139_my_ptr, bmlocal140_my_bitoff, 32, in_val, 0x00000000 );\
	}\
}

// DnDUtils_Statistics_NumberOfMessagesInQueue: IS_DEFAULT accessor is not defined because no default value was specified.
// DnDUtils_Statistics_NumberOfMessagesInQueue: SET_DEFAULT accessor is not defined because no default value was specified.
// DnDUtils_Statistics_NumberOfMessagesInQueue: IS_RESET accessor is not defined because no reset value was specified.
// DnDUtils_Statistics_NumberOfMessagesInQueue: SET_RESET accessor is not defined because no reset value was specified.
// DnDUtils_Statistics_NumberOfMessagesInQueue: CLEAR accessor is not defined because of incompatible access rights. Specified: RW Required: W1C, WO1C.
// DnDUtils_Statistics_NumberOfMessagesInQueue: SET(W1S) accessor is not defined because of incompatible access rights. Specified: RW Required: W1S, WO1S.
#define BM_DnDUtils_Statistics_NumberOfMessagesInQueue_DUMP_DEPTH( base_ptr, depth )\
{\
	/*lint --e{*} */\
	UINT32 bmlocal141_out_val;\
	BM_DnDUtils_Statistics_NumberOfMessagesInQueue_GET( base_ptr, bmlocal141_out_val );\
	/*lint -e(571) */\
	BMI_FORMAT_DUMP(depth, "NumberOfMessagesInQueue", 32, (UINT)(bmlocal141_out_val), "%d", 1);\
}

#define BM_DnDUtils_Statistics_NumberOfMessagesInQueue_DUMP( base_ptr )\
{\
	/*lint --e{*} */\
	BM_DnDUtils_Statistics_NumberOfMessagesInQueue_DUMP_DEPTH( base_ptr, 0 );\
}

#define BM_DnDUtils_Statistics_NumberOfMessagesInQueue_INCREMENT( base_ptr )\
{\
	/*lint --e{*} */\
	PVOID bmlocal142_my_ptr;\
	UINT bmlocal143_my_bitoff;\
	BM_DnDUtils_Statistics_NumberOfMessagesInQueue_GET_POS( base_ptr, bmlocal142_my_ptr, bmlocal143_my_bitoff );\
	(*((UINT32*)bmlocal142_my_ptr))++;\
	BMI_UNUSED_VAR( bmlocal143_my_bitoff );\
}

// DnDUtils_Statistics_NumberOfMessagesInQueue: Validation accessors are not defined because validation condition was not specified.
#define BM_DnDUtils_Statistics_NumberOfMessagesInQueue_GET_BYTES_SIZE( base_ptr, out_bytes )\
{\
	/*lint --e{*} */\
	UINT bmlocal144_tmp_bits;\
	BM_DnDUtils_Statistics_NumberOfMessagesInQueue_GET_SIZE( base_ptr, out_bytes, bmlocal144_tmp_bits );\
	BMI_ROUND_UP_1BYTES( out_bytes, bmlocal144_tmp_bits );\
}

#define BM_DnDUtils_Statistics_NumberOfMessagesInQueue_BYTES_SIZE 4

#define BM_DnDUtils_Statistics_CurrentFileIndex_GET_POS( base_ptr, out_ptr, out_bitoff )\
{\
	/*lint --e{*} */\
	UINT bmlocal147_acc_bytes;\
	UINT bmlocal148_acc_bits;\
	out_ptr = base_ptr;\
	out_bitoff = 0;\
	bmlocal147_acc_bytes = 20;\
	bmlocal148_acc_bits = 0;\
	BMI_ADD_ASSIGN_PTR( out_ptr, bmlocal147_acc_bytes );\
	out_bitoff += bmlocal148_acc_bits;\
}

#define BM_DnDUtils_Statistics_CurrentFileIndex_GET_POS_ALIGNED( base_ptr, out_ptr )\
{\
	/*lint --e{*} */\
	UINT bmlocal149_tmp_bitoff;\
	BM_DnDUtils_Statistics_CurrentFileIndex_GET_POS( base_ptr, out_ptr, bmlocal149_tmp_bitoff );\
	BMI_NORMALIZE_BITOFF(out_ptr, bmlocal149_tmp_bitoff);\
}

#define BM_DnDUtils_Statistics_CurrentFileIndex_POS_ALIGNED 20

// Alignment of DnDUtils_Statistics_CurrentFileIndex: accumulated=(0,0, ABA=4), parent.base=(0,0, ABA=4)
#define BM_DnDUtils_Statistics_CurrentFileIndex_GET_SIZE( base_ptr, out_bytes, out_bits )\
{\
	/*lint --e{*} */\
	out_bytes = 4;\
	out_bits = 0;\
	BMI_UNUSED_VAR( base_ptr );\
}

#define BM_DnDUtils_Statistics_CurrentFileIndex_GET( base_ptr, out_val )\
{\
	/*lint --e{*} */\
	PVOID bmlocal150_my_ptr;\
	UINT bmlocal151_my_bitoff;\
	BM_DnDUtils_Statistics_CurrentFileIndex_GET_POS( base_ptr, bmlocal150_my_ptr, bmlocal151_my_bitoff );\
	if( BMI_MACHINE_ARM_LITTLE == BMI_MACHINE_VALUE )\
	{\
		(out_val) = (UINT16)BMI_32BIT_EXTRACT( (BMI_GET_32BIT_PTR_CONTENTS( BMI_PTR_TO_NUMERIC_CAST(bmlocal150_my_ptr)) ), 0, 32, 0);\
	}\
	else if( BMI_MACHINE_INTEL_LITTLE == BMI_MACHINE_VALUE )\
	{\
		(out_val) = (UINT16)BMI_32BIT_EXTRACT( (BMI_GET_32BIT_PTR_CONTENTS( BMI_PTR_TO_NUMERIC_CAST(bmlocal150_my_ptr)) ), 0, 32, 0);\
	}\
	else\
	{\
		BMI_GENERIC_32BIT_LITTLE_GET( bmlocal150_my_ptr, bmlocal151_my_bitoff, 32, UINT16, out_val, 0x00000000 );\
	}\
}

BMI_INLINE UINT16 BM_INLINE_DnDUtils_Statistics_CurrentFileIndex_GET(PVOID base_ptr)
{
	/*lint --e{*} */
	UINT16 bmlocal152_tmp_var;
	BM_DnDUtils_Statistics_CurrentFileIndex_GET( base_ptr, bmlocal152_tmp_var );
	return bmlocal152_tmp_var;
}

#define BM_DnDUtils_Statistics_CurrentFileIndex_SET( base_ptr, in_val )\
{\
	/*lint --e{*} */\
	PVOID bmlocal153_my_ptr;\
	UINT bmlocal154_my_bitoff;\
	BM_DnDUtils_Statistics_CurrentFileIndex_GET_POS( base_ptr, bmlocal153_my_ptr, bmlocal154_my_bitoff );\
	if( BMI_MACHINE_ARM_LITTLE == BMI_MACHINE_VALUE )\
	{\
		BMI_32BIT_CLEAR_ASSIGN_TYPE( BMI_GET_32BIT_PTR_CONTENTS( BMI_PTR_TO_NUMERIC_CAST(bmlocal153_my_ptr) ), (in_val), 0, 0, 32, UINT32 );\
	}\
	else if( BMI_MACHINE_INTEL_LITTLE == BMI_MACHINE_VALUE )\
	{\
		BMI_32BIT_CLEAR_ASSIGN_TYPE( BMI_GET_32BIT_PTR_CONTENTS( BMI_PTR_TO_NUMERIC_CAST(bmlocal153_my_ptr) ), (in_val), 0, 0, 32, UINT32 );\
	}\
	else\
	{\
		BMI_GENERIC_32BIT_LITTLE_SET( bmlocal153_my_ptr, bmlocal154_my_bitoff, 32, in_val, 0x00000000 );\
	}\
}

// DnDUtils_Statistics_CurrentFileIndex: IS_DEFAULT accessor is not defined because no default value was specified.
// DnDUtils_Statistics_CurrentFileIndex: SET_DEFAULT accessor is not defined because no default value was specified.
// DnDUtils_Statistics_CurrentFileIndex: IS_RESET accessor is not defined because no reset value was specified.
// DnDUtils_Statistics_CurrentFileIndex: SET_RESET accessor is not defined because no reset value was specified.
// DnDUtils_Statistics_CurrentFileIndex: CLEAR accessor is not defined because of incompatible access rights. Specified: RW Required: W1C, WO1C.
// DnDUtils_Statistics_CurrentFileIndex: SET(W1S) accessor is not defined because of incompatible access rights. Specified: RW Required: W1S, WO1S.
#define BM_DnDUtils_Statistics_CurrentFileIndex_DUMP_DEPTH( base_ptr, depth )\
{\
	/*lint --e{*} */\
	UINT16 bmlocal155_out_val;\
	BM_DnDUtils_Statistics_CurrentFileIndex_GET( base_ptr, bmlocal155_out_val );\
	/*lint -e(571) */\
	BMI_FORMAT_DUMP(depth, "CurrentFileIndex", 32, (UINT)(bmlocal155_out_val), "%d", 1);\
}

#define BM_DnDUtils_Statistics_CurrentFileIndex_DUMP( base_ptr )\
{\
	/*lint --e{*} */\
	BM_DnDUtils_Statistics_CurrentFileIndex_DUMP_DEPTH( base_ptr, 0 );\
}

#define BM_DnDUtils_Statistics_CurrentFileIndex_INCREMENT( base_ptr )\
{\
	/*lint --e{*} */\
	PVOID bmlocal156_my_ptr;\
	UINT bmlocal157_my_bitoff;\
	BM_DnDUtils_Statistics_CurrentFileIndex_GET_POS( base_ptr, bmlocal156_my_ptr, bmlocal157_my_bitoff );\
	(*((UINT32*)bmlocal156_my_ptr))++;\
	BMI_UNUSED_VAR( bmlocal157_my_bitoff );\
}

// DnDUtils_Statistics_CurrentFileIndex: Validation accessors are not defined because validation condition was not specified.
#define BM_DnDUtils_Statistics_CurrentFileIndex_GET_BYTES_SIZE( base_ptr, out_bytes )\
{\
	/*lint --e{*} */\
	UINT bmlocal158_tmp_bits;\
	BM_DnDUtils_Statistics_CurrentFileIndex_GET_SIZE( base_ptr, out_bytes, bmlocal158_tmp_bits );\
	BMI_ROUND_UP_1BYTES( out_bytes, bmlocal158_tmp_bits );\
}

#define BM_DnDUtils_Statistics_CurrentFileIndex_BYTES_SIZE 4

#define BM_DnDUtils_Statistics_GET_SIZE( base_ptr, out_bytes, out_bits )\
{\
	/*lint --e{*} */\
	out_bytes = 24;\
	out_bits = 0;\
	BMI_UNUSED_VAR( base_ptr );\
}

#define BM_DnDUtils_Statistics_GET_BYTES_SIZE( base_ptr, out_bytes )\
{\
	/*lint --e{*} */\
	UINT bmlocal161_tmp_bits;\
	BM_DnDUtils_Statistics_GET_SIZE( base_ptr, out_bytes, bmlocal161_tmp_bits );\
	BMI_ROUND_UP_1BYTES( out_bytes, bmlocal161_tmp_bits );\
}

#define BM_DnDUtils_Statistics_BYTES_SIZE 24

#define BM_DnDUtils_Statistics_DUMP_DEPTH( base_ptr, depth )\
{\
	/*lint --e{*} */\
	BMI_FORMAT_NONVALUE_DUMP(depth, "DnDUtils_Statistics", 1);\
	BM_DnDUtils_Statistics_TotalNumOfMessages_DUMP_DEPTH( base_ptr, (depth + 1) );\
	BM_DnDUtils_Statistics_TotalSizeInBytes_DUMP_DEPTH( base_ptr, (depth + 1) );\
	BM_DnDUtils_Statistics_LastMessageSizeInBytes_DUMP_DEPTH( base_ptr, (depth + 1) );\
	BM_DnDUtils_Statistics_NumberOfLostMessagesRaised_DUMP_DEPTH( base_ptr, (depth + 1) );\
	BM_DnDUtils_Statistics_NumberOfMessagesInQueue_DUMP_DEPTH( base_ptr, (depth + 1) );\
	BM_DnDUtils_Statistics_CurrentFileIndex_DUMP_DEPTH( base_ptr, (depth + 1) );\
	BMI_UNUSED_VAR( base_ptr );\
}

#define BM_DnDUtils_Statistics_DUMP( base_ptr )\
{\
	/*lint --e{*} */\
	BM_DnDUtils_Statistics_DUMP_DEPTH( base_ptr, 0 );\
}


/*lint --flb */

#endif /* _BITMAN_L4MONITORGROUPS_H_ */

