/*****************************************************************************
 * Automatically generated by Bitman2Base V4.2.5.0 (5.0) Bitman2 (exe) V4.2.5.0 (5.0) - DO NOT EDIT!
 * Generated at 11/19/2009 12:56:00 AM
 *
 * Project : Ofer
 * Module  : L2L3 API Descriptors
 * Author  : Simon Kamenkovich
 * Date    : 10/11/2005
 * Purpose : L2 L3 API descriptors, related to Ranging 
 *****************************************************************************/

#if !defined(_BITMAN_L2L3_API_RANGING_ENUMS_H_)
#define _BITMAN_L2L3_API_RANGING_ENUMS_H_


/*lint ++flb */
// Include headers generated from XMLs (the source is both XMLs and the command-line)

// Include user C header files


// Bitman version Accessor...
#ifndef BM_BITMAN_VERSION
#define BM_BITMAN_VERSION 	"Bitman2Base V4.2.5.0 (5.0) Bitman2 (exe) V4.2.5.0 (5.0)"
#endif 

// Definitions

typedef enum
{
	RANGING_MODE_INVALID = 0,
	RANGING_MODE_INITIAL = 1,
	RANGING_MODE_PERIODIC = 2,
	RANGING_MODE_HO_DROP = 3,
	RANGING_MODE_HO_COORDINATED = 4,
	RANGING_MODE_LOCATION_UPDATE = 5,
	RANGING_MODE_EXIT_IDLE = 6,
	RANGING_MODE_NO_RANGING = 7
} ERangingMode;

typedef enum
{
	L2_RANGING_STATUS_SUCCESS = 1,
	L2_RANGING_STATUS_FAILURE_NW_ABORTED = 2,
	L2_RANGING_STATUS_FAILURE_RRC_EXHAUSTED = 3,
	L2_RANGING_STATUS_FAILURE_ARC_EXHAUSTED = 4,
	L2_RANGING_STATUS_FAILURE_CDMA_TO = 5,
	L2_RANGING_STATUS_FAILURE_RANGING_RESET = 6,
	L2_RANGING_STATUS_MAC_TO = 7
} ERangingStatus;

/*lint --flb */

#endif /* _BITMAN_L2L3_API_RANGING_ENUMS_H_ */

