/*****************************************************************************
 * Automatically generated by Bitman2Base V4.2.5.0 (5.0) Bitman2 (exe) V4.2.5.0 (5.0) - DO NOT EDIT!
 * Generated at 11/19/2009 12:56:06 AM
 *
 * Project : Ofer
 * Module  : Trace Modules Definition
 * Author  : Vaknin Yaron
 * Date    : 28/08/2005
 * Purpose : OFER Trace Modules Definitions
 *****************************************************************************/

#if !defined(_BITMAN_TRACEMODULES_H_)
#define _BITMAN_TRACEMODULES_H_


/*lint ++flb */
// Include headers generated from XMLs (the source is both XMLs and the command-line)

// Include user C header files

// Include user C header files (supplied in the command-line)


// Bitman version Accessor...
#ifndef BM_BITMAN_VERSION
#define BM_BITMAN_VERSION 	"Bitman2Base V4.2.5.0 (5.0) Bitman2 (exe) V4.2.5.0 (5.0)"
#endif 

// Definitions

#define UNKNOWN_MODULE_LOG (07)

// NETWORK CTRL
#define MEASURMENT_MODULE_LOG (09)

// NETWORK CTRL
#define OSAL_MODULE_LOG (10)

// NETWORK CTRL
#define HDI_MODULE_LOG (15)

// NETWORK CTRL
#define AIFAL_ADAPTER_LOG (20)

// NETWORK CTRL
#define HDI_ADAPTER_LOG (21)

// NETWORK CTRL
#define IOCTL_ADAPTER_LOG (22)

// NETWORK CTRL
#define PACKET_BRIDGE_ADAPTER_LOG (23)

// NETWORK CTRL
#define SOCKET_ADAPTER_LOG (24)

// NETWORK CTRL
#define TRACE_ADAPTER_LOG (25)

// NETWORK CTRL
#define L4_ADAPTER_LOG (26)

// MONITOR CTRL
#define PROFILER_MODULE_LOG (28)

// MONITOR CTRL
#define MONITOR_MODULE_LOG (29)

// NETWORK CTRL
#define PAL_MODULE_LOG (30)

// NETWORK CTRL
#define DBUPDATE_MODULE_LOG (31)

// NETWORK CTRL
#define MEMORYMANAGER_MODULE_LOG (32)

// NETWORK CTRL
#define MOC_MODULE_LOG (33)

// NETWORK CTRL
#define PAL_DEBUG_MODULE_LOG (34)

// NETWORK CTRL
#define TIMERS_MODULE_LOG (35)

// NETWORK CTRL
#define TRACE_MODULE_LOG (36)

// NETWORK CTRL
#define VERSIONS_MODULE_LOG (37)

// NETWORK CTRL
#define FRAMEWORKBACKPLANE_MODULE_LOG (38)

// NETWORK CTRL
#define TIKA_DM_MODULE_LOG (39)

// NETWORK CTRL
#define TIKA_UM_MODULE_LOG (40)

// NETWORK CTRL
#define TIKA_KM_MODULE_LOG (41)

// NETWORK CTRL
#define TIKA_FW_MODULE_LOG (42)

// NETWORK CTRL
#define TIKA_UD_MODULE_LOG (43)

// UMAC RX data mdule log
#define UMAC_RX_DATA_MDULE_LOG (44)

// UMAC RX ARQ mdule log
#define UMAC_RX_ARQ_MDULE_LOG (45)

// UMAC RX controller mdule log
#define UMAC_RX_CONTROLLER_MDULE_LOG (46)

// UMAC RX database mdule log
#define UMAC_RX_DATABASE_MDULE_LOG (47)

// UMAC RX defrag mdule log
#define UMAC_RX_DEFRAG_MDULE_LOG (48)

// UMAC RX dePHS mdule log
#define UMAC_RX_DEPHS_MDULE_LOG (49)

// UMAC RX pdu parser mdule log
#define UMAC_RX_PDU_PARSER_MDULE_LOG (50)

// UMAC RX sequencer mdule log
#define UMAC_RX_SEQUENCER_MDULE_LOG (51)

// UMAC RX utils mdule log
#define UMAC_RX_UTILS_MDULE_LOG (52)

// UMAC RX PDU reorder mdule log
#define UMAC_RX_PDU_REORDER_MDULE_LOG (53)

// UMAC TX data mdule log
#define UMAC_TX_DATA_MDULE_LOG (54)

// UMAC TX ARQ mdule log
#define UMAC_TX_ARQ_MDULE_LOG (55)

// UMAC TX classifier mdule log
#define UMAC_TX_CLASSIFIER_MDULE_LOG (56)

// UMAC TX PHS mdule log
#define UMAC_TX_PHS_MDULE_LOG (57)

// UMAC CTRL data mdule log
#define UMAC_CTRL_DATA_MDULE_LOG (58)

// UMAC CTRL DSPS framework log
#define UMAC_CTRL_DSPS_FRAMEWORK_LOG (59)

// UMAC CTRL ping protocol log
#define UMAC_CTRL_PING_PROTOCOL_LOG (60)

// UMAC CTRL management auto sender log
#define UMAC_CTRL_MGMT_AUTO_SENDER_LOG (61)

// UMAC CTRL MAC messages parsers log
#define UMAC_CTRL_MAC_PARSER_LOG (62)

// UMAC CTRL management gateway log
#define UMAC_CTRL_MGMT_GW_MDULE_LOG (63)

// UMAC CTRL platform controller log
#define UMAC_CTRL_PLATFORM_CONTROLLER_MDULE_LOG (64)

// UMAC CTRL L3 control log
#define UMAC_CTRL_L3CONTROL_MDULE_LOG (65)

// UMAC CTRL L3 mobility manager log
#define UMAC_CTRL_MOBILITY_MANAGER_MDULE_LOG (66)

// UMAC CTRL BS selection log
#define UMAC_CTRL_MB_MGR_BS_SELECTION_MDULE_LOG (67)

// UMAC CTRL calibration log
#define UMAC_CTRL_MB_MGR_CALIBRATION_MDULE_LOG (68)

// UMAC CTRL CDM log
#define UMAC_CTRL_MB_MGR_CDM_MDULE_LOG (69)

// UMAC CTRL context database log
#define UMAC_CTRL_MB_MGR_CONTEXT_DB_MDULE_LOG (70)

// UMAC CTRL HO initiator and Indicator log
#define UMAC_CTRL_MB_MGR_HO_MSG_HANDLERS_MDULE_LOG (71)

// UMAC CTRL HO triggers log
#define UMAC_CTRL_MB_MGR_HO_TRIGGERS_MDULE_LOG (72)

// UMAC CTRL IMM log
#define UMAC_CTRL_MB_MGR_IMM_MDULE_LOG (73)

// UMAC CTRL MOB NBR ADV PARSER log
#define UMAC_CTRL_MB_NBR_ADV_PARSER_LOG (74)

// UMAC CTRL L3 link integrity log
#define UMAC_CTRL_MB_MGR_L3LINK_INTEGRITY_MDULE_LOG (75)

// UMAC CTRL L3 scan log
#define UMAC_CTRL_MB_MGR_L3_SCAN_MDULE_LOG (76)

// UMAC CTRL plan maker log
#define UMAC_CTRL_MB_MGR_PLAN_MAKER_MDULE_LOG (77)

// UMAC CTRL upper data state shifter log
#define UMAC_CTRL_MB_MGR_UPPER_DATA_STATE_SHIFTER_MDULE_LOG (78)

// UMAC CTRL L3 ranger log
#define UMAC_CTRL_MB_MGR_L3_RANGER_MDULE_LOG (79)

// UMAC CTRL Network manager log
#define UMAC_CTRL_NW_MGR_MDULE_LOG (80)

// UMAC CTRL DREG log
#define UMAC_CTRL_NW_MGR_DREG_MDULE_LOG (81)

// UMAC CTRL DSX log
#define UMAC_CTRL_NW_MGR_DSX_MDULE_LOG (82)

// UMAC CTRL Registration log
#define UMAC_CTRL_NW_MGR_REGISTRATION_MDULE_LOG (83)

// UMAC CTRL Reset Cmd log
#define UMAC_CTRL_NW_MGR_RESET_MDULE_LOG (84)

// UMAC CTRL SBC log
#define UMAC_CTRL_NW_MGR_SBC_MDULE_LOG (85)

// UMAC CTRL security log
#define UMAC_CTRL_NW_MGR_SECURITY_MDULE_LOG (86)

// UMAC CTRL SFM log
#define UMAC_CTRL_NW_MGR_SFM_MDULE_LOG (87)

// UMAC CTRL scan packet sequencer log
#define UMAC_CTRL_MB_MGR_SPS_MDULE_LOG (88)

// UMAC CTRL PLIS log
#define UMAC_CTRL_PLIS_MDULE_LOG (89)

// UMAC CTRL policy manager log
#define UMAC_CTRL_MB_MGR_POLICY_MANAGER_MDULE_LOG (90)

// UMAC CTRL idle profiler
#define UMAC_CTRL_MB_MGR_IDLE_PROFILER_MDULE_LOG (91)

// UMAC control AcSel log
#define UMAC_CTRL_MB_MGR_ACSEL_LOG (92)

// UMAC CTRL Coexistence module log
#define UMAC_CTRL_COEX_MDULE_LOG (93)

// UMAC Crypto Service
#define UMAC_CRYPTO_MODULE_LOG (94)

// Watch Dog Timer module
#define UMAC_CTRL_WATCH_DOG_TIMER_MDULE_LOG (95)

// UMAC CTRL Detect BS Vendor log
#define UMAC_CTRL_MB_MGR_DETECT_BS_VENDOR_MDULE_LOG (96)

// UMAC TX ERTPS mdule log
#define UMAC_TX_ERTPS_MDULE_LOG (97)

// UMAC TX Rate Limiter module log
#define UMAC_TX_RATE_LIMITER_MDULE_LOG (98)

// UMAC CTRL ptcm log
#define UMAC_CTRL_MB_PHY_TRIGGER_CONF_MUX_LOG (99)

// Regulatory module log
#define UMAC_CTRL_MB_REGULATORY_LOG (100)

// UMAC MEMBER - ITS FOR U, USE IT
#define UMAC_RESERVED4_LOG (101)

// UMAC MEMBER - ITS FOR U, USE IT
#define UMAC_RESERVED3_LOG (102)

// UMAC MEMBER - ITS FOR U, USE IT
#define UMAC_RESERVED2_LOG (103)

// UMAC MEMBER - ITS FOR U, USE IT
#define UMAC_RESERVED1_LOG (104)

// FW general log
#define FW_GENERAL_MDULE_LOG (110)

// FW TX data general log
#define FW_TX_DATA_MDULE_LOG (111)

// FW TX data BWR log
#define FW_TX_BWR_MDULE_LOG (112)

// FW TX data FAP log
#define FW_TX_FAP_MDULE_LOG (113)

// FW TX data Hdi Eat log
#define FW_TX_HDI_EAT_MDULE_LOG (114)

// FW TX data Lower QOS log
#define FW_TX_LQOS_MDULE_LOG (115)

// FW TX data Lower Controller log
#define FW_TX_LCONTROLLER_MDULE_LOG (116)

// FW TX data Lower Sequencer log
#define FW_TX_LSEQUENCER_MDULE_LOG (117)

// FW TX data Map Handler log
#define FW_TX_MAP_HANDLER_MDULE_LOG (118)

// FW TX data Sdu Manager log
#define FW_TX_SDU_MANAGER_MDULE_LOG (119)

// FW TX data VQ log
#define FW_TX_VQ_MDULE_LOG (120)

// FW TX data SDU Agent log
#define FW_TX_SDU_AGENT_MDULE_LOG (121)

// FW RX data general log
#define FW_RX_DATA_MDULE_LOG (122)

// FW Control general log
#define FW_CONTROL_MDULE_LOG (123)

// FW Control CDMA log
#define FW_CONTROL_CDMA_MDULE_LOG (124)

// FW Control Initial Ranging log
#define FW_CONTROL_RANGING_MDULE_LOG (125)

// FW Control Initial Scan log
#define FW_CONTROL_SCAN_MDULE_LOG (126)

// FW Control L2C log
#define FW_CONTROL_L2C_MDULE_LOG (127)

// FW Control L2LSI log
#define FW_CONTROL_L2LSI_MDULE_LOG (128)

// FW DCD UCD log
#define FW_CONTROL_DCD_UCD_MDULE_LOG (129)

// FW Control L2C log
#define FW_CONTROL_FRAME_TICK_MDULE_LOG (130)

// FW Control ELCG interface log
#define FW_CONTROL_ELCG_INTERFACE_MDULE_LOG (131)

// FW TxDb module log
#define FW_TX_DB_MDULE_LOG (132)

// FW Test Modes general log
#define FW_TESTS_MODE_MDULE_LOG (133)

// FW Test Modes Stress log
#define FW_TESTS_MODE_STRESS_MDULE_LOG (134)

// FW Init general log
#define FW_INIT_MDULE_LOG (135)

// FW TX data general log
#define FW_PLATFORM_CONTROL_MDULE_LOG (136)

// FW User Indication (LEDs) log
#define FW_PLATFORM_CONTROL_USER_INDICATION_MDULE_LOG (137)

// FW Control LAM log
#define FW_CONTROL_LAM_LOG (138)

// FW DMM module log
#define FW_DMM_MDULE_LOG (139)

// FW WDT module log
#define FW_PLATFORM_CONTROL_WDT_LOG (140)

// FW MEMBER - ITS FOR U, USE IT
#define FW_RESERVED5_LOG (141)

// FW MEMBER - ITS FOR U, USE IT
#define FW_RESERVED4_LOG (142)

// FW MEMBER - ITS FOR U, USE IT
#define FW_RESERVED3_LOG (143)

// FW MEMBER - ITS FOR U, USE IT
#define FW_RESERVED2_LOG (144)

// FW MEMBER - ITS FOR U, USE IT
#define FW_RESERVED1_LOG (145)

// HAL general log
#define HAL_GENERAL_MDULE_LOG (151)

// HAL ELCG log
#define HAL_ELCG_MDULE_LOG (152)

// HAL PUMA log
#define HAL_PUMA_MDULE_LOG (153)

// HAL PLC log
#define HAL_PLC_MDULE_LOG (154)

// SDILLO DL log - This has to be the first SDILLO module !
#define SDILLO_DL_MDULE_LOG (158)

// SDILLO queues log
#define SDILLO_QUEUES_MDULE_LOG (159)

// SDILLO Task Sequencer log
#define SDILLO_TS_MDULE_LOG (160)

// SDILLO Map Parser log
#define SDILLO_MP_MDULE_LOG (161)

// SDILLO DL Map Parser log
#define SDILLO_MP_DL_MDULE_LOG (162)

// SDILLO UL Map Parser log
#define SDILLO_MP_UL_MDULE_LOG (163)

// SDILLO set-mode log
#define SDILLO_DCD_UCD_MDULE_LOG (164)

// SDILLO ranging log
#define SDILLO_RANGING_MDULE_LOG (165)

// SDILLO PDU log
#define SDILLO_PDU_MDULE_LOG (166)

// SDILLO burst log
#define SDILLO_BURST_MDULE_LOG (167)

// SDILLO DL Burst manager log
#define SDILLO_DBM_MDULE_LOG (168)

// SDILLO CID configuration log
#define SDILLO_CID_CONFIG_LOG (169)

// SDILLO DL HARQ State-machine log
#define SDILLO_HARQ_DL_MDULE_LOG (170)

// SDILLO UL HARQ State-machinelog
#define SDILLO_HARQ_UL_MDULE_LOG (171)

// SDILLO FFB log
#define SDILLO_FFB_MDULE_LOG (172)

// SDILLO RX descriptor log
#define SDILLO_RX_DESC_MDULE_LOG (173)

// SDILLO CINR log
#define SDILLO_CINR_MDULE_LOG (174)

// SDILLO scheduler log
#define SDILLO_SCHEDULER_MDULE_LOG (175)

// SDILLO interframe power save log
#define SDILLO_IFPS_MDULE_LOG (176)

// SDILLO ARM I/F log
#define SDILLO_ARM_IF_MDULE_LOG (177)

// SDILLO HALs log
#define SDILLO_HALS_MDULE_LOG (178)

// SDILLO general log
#define SDILLO_GENERAL_MDULE_LOG (179)

// SDILLO Real Time log
#define SDILLO_RT_MDULE_LOG (180)

// SDILLO Production log
#define SDILLO_PRODUCTION_MDULE_LOG (181)

// SDILLO Monitoring log
#define SDILLO_MONITORING_MDULE_LOG (182)

// SDILLO State log
#define SDILLO_STATE_MDULE_LOG (183)

// SDILLO time adjustment log
#define SDILLO_TIME_ADJUST_MDULE_LOG (184)

// SDILLO reserved5 log
#define SDILLO_RESERVED5_LOG (185)

// SDILLO reserved4 log
#define SDILLO_RESERVED4_LOG (186)

// SDILLO reserved3 log
#define SDILLO_RESERVED3_LOG (187)

// SDILLO reserved2 log
#define SDILLO_RESERVED2_LOG (188)

// SDILLO reserved1 log
#define SDILLO_RESERVED1_LOG (189)

// SDILLO UL log - This has to be the last SDILLO module !
#define SDILLO_UL_MDULE_LOG (190)

// L1FW General
#define L1FW_GENERAL_LOG (196)

// L1 Initialization Code
#define L1FW_INIT_LOG (197)

// L1 Controller
#define L1FW_L1C_LOG (198)

// Initial Scan
#define L1FW_INITIAL_SCAN_LOG (199)

// Calibration
#define L1FW_CALIBRATION_LOG (200)

// Automatic Gain Control
#define L1FW_AGC_LOG (201)

// Modem HAL
#define L1FW_HAL_LOG (202)

// SDillo Interface
#define L1FW_DILLO_IF_LOG (203)

// LTA L1 Test Agent
#define L1FW_LTA_LOG (204)

// Time Tracking
#define L1FW_TIME_TRACKING_LOG (205)

// Frequency Tracking
#define L1FW_FREQ_TRACKING_LOG (206)

// TPC Controller
#define L1FW_TPC_CONTROL_LOG (207)

// TPC Proces
#define L1FW_TPC_PROCESS_LOG (208)

// PHY Triggers
#define L1FW_PHY_TRIGGERS_LOG (209)

// Modem HW Error
#define L1FW_ERROR_HANDLER_LOG (210)

// Periodic Scanning Management
#define L1FW_PERIODIC_SCAN_MNGMNT_LOG (211)

// L1 Report Agent
#define L1FW_L1_REPORT_AGENT_LOG (212)

// Production Controller
#define PRCTRL_LOG (213)

// N/A
#define L1FW_MEASUREMENTS_LOG (214)

// Fddc Xcorr manager
#define L1FW_FDDC_XCORR_LOG (215)

// L1 Thermal Manager
#define L1FW_THERMAL_MNGR_LOG (216)

// Resync
#define L1FW_RESYNC_LOG (217)

// Channel initialization utile
#define L1FW_CHAN_INIT_UTILE_LOG (218)

// L1 hand over manager
#define L1FW_HO_MNGR_LOG (219)

// Phy Triggers Manager
#define L1FW_L1DB_LOG (220)

// FW Control L2 scheduler log
#define FW_CONTROL_L2SCHEDULER_MDULE_LOG (221)

// Periodic Scanning Process
#define L1FW_PERIODIC_SCAN_PROC_LOG (222)

// Temperature and PA measurements manager module
#define L1FW_TPMM_LOG (223)

// Calibration triggers manager Process
#define L1FW_CTM_PROC_LOG (224)

// L1 Idle mode manager
#define L1FW_IDLE_MODE_MANAGER_LOG (225)

// L1 Pa measurments module
#define L1FW_PAMSR_LOG (226)

// L1 TempMsr Cntrl and Utiles
#define L1FW_TEMPERATURE_MEASURE_LOG (227)

// L1 Dc Block Filter Maneger module
#define L1FW_DCFM_LOG (228)

// Chmm and friends module
#define L1FW_RSSI_CINR_MEASURE_LOG (229)

// L1 WiMAX-BT Coexistence signaling module
#define L1FW_BT_COEX_LOG (230)

// L1FW MEMBER - ITS FOR U, USE IT
#define L1FW_RESERVED2_LOG (231)

// L1FW MEMBER - ITS FOR U, USE IT
#define L1FW_RESERVED1_LOG (232)

/*lint --flb */

#endif /* _BITMAN_TRACEMODULES_H_ */

