#pragma once

#define OID_GLN_OBJ_OPER        0xff100000

#define OID_GLN_REGISTER_PROFILE_SERVICE            (OID_GLN_OBJ_OPER | 0x00000018)

#define OID_GLN_CISCO_LEAP_ROGUE_MODE               (OID_GLN_OBJ_OPER | 0x00000034) 
#define OID_GLN_CISCO_CWMIN_CWMAX                   (OID_GLN_OBJ_OPER | 0x00000039)
#define OID_GLN_CISCO_MIXED_CELLS_MODE              (OID_GLN_OBJ_OPER | 0x00000040)
#define OID_GLN_CISCO_TPC                           (OID_GLN_OBJ_OPER | 0x00000041)
#define OID_GLN_CISCO_ASSISTED_ROAMING              (OID_GLN_OBJ_OPER | 0x00000042)
#define OID_GLN_CISCO_CCKM                          (OID_GLN_OBJ_OPER | 0x00000043)
#define OID_GLN_CISCO_RADIO_MEASURMENTS             (OID_GLN_OBJ_OPER | 0x00000044)
#define OID_GLN_CISCO_CCX_VERSION                   (OID_GLN_OBJ_OPER | 0x00000045)
#define OID_GLN_CISCO_QoS_PARAMETER_SET_IE          (OID_GLN_OBJ_OPER | 0x00000046)

/* definitions for OID_GLN_REGISTER_PROFILE_SERVICE */
#define GLN_REGISTER_PROFILE_SERVICE				1
#define GLN_UNREGISTER_PROFILE_SERVICE				0      
