// 
// .\..\..\\OSAgnostic\Common\CommonServices\Versions.h : This file contains all PIPE versions defines
// 
// Auto generated by version.pl at Mon Dec 28 21:48:36 2009

#ifndef VERSIONS_H_ 
#define VERSIONS_H_ 

// APPSRV Version 5.10.1047.0.0
#define APPSRV_MAJOR    5;
#define APPSRV_MINOR    10;
#define APPSRV_BUILD    1047;
#define APPSRV_REVISION 0;
#define APPSRV_BRANCH   0;


// PIPE_HANDLER Version 5.10.1047.0.0
#define PIPE_HANDLER_MAJOR    5;
#define PIPE_HANDLER_MINOR    10;
#define PIPE_HANDLER_BUILD    1047;
#define PIPE_HANDLER_REVISION 0;
#define PIPE_HANDLER_BRANCH   0;


// MOC_HANDLER Version 5.10.1047.0.0
#define MOC_HANDLER_MAJOR    5;
#define MOC_HANDLER_MINOR    10;
#define MOC_HANDLER_BUILD    1047;
#define MOC_HANDLER_REVISION 0;
#define MOC_HANDLER_BRANCH   0;


// IWMXSDK Version 5.10.1047.0.0
#define IWMXSDK_MAJOR    5;
#define IWMXSDK_MINOR    10;
#define IWMXSDK_BUILD    1047;
#define IWMXSDK_REVISION 0;
#define IWMXSDK_BRANCH   0;


// GENERIC Version 5.10.1047.0.0
#define GENERIC_MAJOR    5;
#define GENERIC_MINOR    10;
#define GENERIC_BUILD    1047;
#define GENERIC_REVISION 0;
#define GENERIC_BRANCH   0;


// DND Version 5.10.1047.0.0
#define DND_MAJOR    5;
#define DND_MINOR    10;
#define DND_BUILD    1047;
#define DND_REVISION 0;
#define DND_BRANCH   0;


// DM Version 5.10.1047.0.0
#define DM_MAJOR    5;
#define DM_MINOR    10;
#define DM_BUILD    1047;
#define DM_REVISION 0;
#define DM_BRANCH   0;


// DBG Version 5.10.1047.0.0
#define DBG_MAJOR    5;
#define DBG_MINOR    10;
#define DBG_BUILD    1047;
#define DBG_REVISION 0;
#define DBG_BRANCH   0;

#endif 
